config/routes.rb
Hrad::Application.routes.draw do
    
  resources :pnameforms do
    resources :piece1s, controller: 'pnameforms/piece1s'
    resources :piece2s, controller: 'pnameforms/piece2s'
    resources :piece3s, controller: 'pnameforms/piece3s'
    resources :piece4s, controller: 'pnameforms/piece4s'
    resources :piece5s, controller: 'pnameforms/piece5s'
    resources :piece6s, controller: 'pnameforms/piece6s'
    resources :piece7s, controller: 'pnameforms/piece7s'
    resources :piece8s, controller: 'pnameforms/piece8s'
    resources :piece9s, controller: 'pnameforms/piece9s'
    resources :piece10s, controller: 'pnameforms/piece10s'
    resources :piece11s, controller: 'pnameforms/piece11s'
    resources :piece12s, controller: 'pnameforms/piece12s'
    resources :piece13s, controller: 'pnameforms/piece13s'
    resources :piece14s, controller: 'pnameforms/piece14s'
    resources :piece15s, controller: 'pnameforms/piece15s'
    resources :piece16s, controller: 'pnameforms/piece16s'
    resources :piece17s, controller: 'pnameforms/piece17s'
    resources :piece18s, controller: 'pnameforms/piece18s'
    resources :piece19s, controller: 'pnameforms/piece19s'
    resources :piece20s, controller: 'pnameforms/piece20s'
    resources :piece21s, controller: 'pnameforms/piece21s'
    resources :piece22s, controller: 'pnameforms/piece22s'
    resources :piece23s, controller: 'pnameforms/piece23s'
    resources :piece24s, controller: 'pnameforms/piece24s'
    resources :piece25s, controller: 'pnameforms/piece25s'
  end     

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :seds do
    resources :plays, controller: 'seds/plays'
    resources :scripts, controller: 'seds/scripts'
  end 
  
  root 'pages#home'

end

app/models/sed.rb
class Sed < ActiveRecord::Base
	has_many :plays, dependent: :destroy 
	has_many :scripts, dependent: :destroy
	
	belongs_to :user 
end

app/controllers/seds/plays_controller.rb
class Seds::PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @sed = Sed.find(params[:sed_id])
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
    @sed = Sed.find(params[:sed_id])
    @plays = Play.all
  end

  # GET /plays/new
  def new
    @sed = Sed.find(params[:sed_id])
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
    @sed = Sed.find(params[:sed_id])
    @play.sed = @sed 
  end

  # POST /plays
  # POST /plays.json
  def create
    @sed = Sed.find(params[:sed_id])
    @play = Play.new(play_params)
    @play.sed = @sed 

    respond_to do |format|
      if @play.save
        format.html { redirect_to @sed, notice: 'Play was successfully added.' }
        format.json { render :show, status: :created, location: @sed }
      else
        format.html { render :new }
        format.json { render json: @sed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    @sed = Sed.find(params[:sed_id])
    @play.sed = @sed 
        
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @sed, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @sed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @sed = Sed.find(params[:sed_id])
    @play = Play.find(params[:id])
    title = @play.fullname  
    
    if @play.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @sed
    else
      flash[:error] = "There was an error deleting the play."
      render :show
    end     
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:piece1, :piece2, :piece3, :piece4, :piece5, :piece6, :piece7, :piece8, :piece9, :piece10, :piece11, :piece12, :piece13, :piece14, :piece15, :piece16, :piece17, :piece18, :piece19, :piece20, :piece21, :piece22, :piece23, :piece24, :piece25, :sed_id)
    end
end

app/controllers/seds_controller.rb
class SedsController < ApplicationController
  before_action :set_sed, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /seds
  # GET /seds.json
  def index
    @seds = Sed.all
  end

  # GET /seds/1
  # GET /seds/1.json
  def show
    @sed = Sed.find(params[:id])
    @plays = @sed.plays
    @scripts = @sed.scripts
  end

  # GET /seds/new
  def new
    @sed = current_user.seds.build 
  end

  # GET /seds/1/edit
  def edit
  end

  # POST /seds
  # POST /seds.json
  def create
    @sed = current_user.seds.build(sed_params)

    respond_to do |format|
      if @sed.save
        format.html { redirect_to @sed, notice: 'Sed was successfully created.' }
        format.json { render :show, status: :created, location: @sed }
      else
        format.html { render :new }
        format.json { render json: @sed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seds/1
  # PATCH/PUT /seds/1.json
  def update
    respond_to do |format|
      if @sed.update(sed_params)
        format.html { redirect_to @sed, notice: 'Sed was successfully updated.' }
        format.json { render :show, status: :ok, location: @sed }
      else
        format.html { render :edit }
        format.json { render json: @sed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seds/1
  # DELETE /seds/1.json
  def destroy
    @sed.destroy
    respond_to do |format|
      format.html { redirect_to seds_url, notice: 'Sed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sed
      @sed = Sed.find(params[:id])
    end

    def correct_user
      redirect_to root_path, notice: "Not authorized" if @sed.user != current_user   
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def sed_params
      params.require(:sed).permit(:name, :user_id)
    end
end

app/helpers/seds_helper.rb
module SedsHelper
end

app/views/seds/_form.html.erb
<%= form_for(@sed) do |f| %>
  <% if @sed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sed.errors.count, "error") %> prohibited this sed from being saved:</h2>

      <ul>
      <% @sed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Create/Update" %>
  </div>
<% end %>

app/views/seds/edit.html.erb
<h1>Editing Session Name</h1>

<%= render 'form' %>

<%= link_to 'Show', @sed %> |
<%= link_to 'Back', seds_path %>

app/views/seds/index.html.erb
<h1>My Sessions</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <tbody>
        <% @seds.each do |sed| %>
          <tr>
            <% if sed.user == current_user %>
              <td><%= sed.name %></td>
              <td><%= link_to 'Open', sed %></td>
              <td><%= link_to 'Edit Session Name', edit_sed_path(sed) %></td>
              <td><%= link_to 'Delete', sed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>  
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>    

<br>

<%= link_to 'New Session', new_sed_path %>

app/views/seds/new.html.erb
<h1>New Session</h1>

<%= render 'form' %>

<%= link_to 'Back', seds_path %>

app/views/seds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sed.name %>
  <%= link_to 'Edit Name', edit_sed_path(@sed), class: 'pull-right' %>
</p>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Install Plays</th>
        </tr>   
      </thead>
      <tbody>
        <% @plays.each do |play| %>
          <tr>
            <td><%= play.fullname %></td>
            <td><%= link_to 'Edit', edit_sed_play_path(@sed, play) %></td>
            <td><%= link_to 'Delete', [@sed, play], method: :delete, confirm: "Are you sure?" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div> 		

<%= link_to "Add new play", new_sed_play_path(@sed), class: 'pull-right' %>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Scripts</th>
        </tr>   
      </thead>
      <tbody>
        <% @scripts.each do |script| %>
          <tr>
            <td><%= script.name %></td>
            <td><%= link_to 'View', sed_script_path(@sed, script) %></td>
            <td><%= link_to 'Edit', edit_sed_script_path(@sed, script) %></td>
            <td><%= link_to 'Delete', [@sed, script], method: :delete, confirm: "Are you sure?" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>  

<%= link_to "Add new script", new_sed_script_path(@sed), class: 'pull-right' %> 


<%= link_to 'Back', seds_path %>