config/routes.rb
Hrad::Application.routes.draw do
    
  resources :pnameforms do
    resources :piece1s, controller: 'pnameforms/piece1s'
    resources :piece2s, controller: 'pnameforms/piece2s'
    resources :piece3s, controller: 'pnameforms/piece3s'
    resources :piece4s, controller: 'pnameforms/piece4s'
    resources :piece5s, controller: 'pnameforms/piece5s'
    resources :piece6s, controller: 'pnameforms/piece6s'
    resources :piece7s, controller: 'pnameforms/piece7s'
    resources :piece8s, controller: 'pnameforms/piece8s'
    resources :piece9s, controller: 'pnameforms/piece9s'
    resources :piece10s, controller: 'pnameforms/piece10s'
    resources :piece11s, controller: 'pnameforms/piece11s'
    resources :piece12s, controller: 'pnameforms/piece12s'
    resources :piece13s, controller: 'pnameforms/piece13s'
    resources :piece14s, controller: 'pnameforms/piece14s'
    resources :piece15s, controller: 'pnameforms/piece15s'
    resources :piece16s, controller: 'pnameforms/piece16s'
    resources :piece17s, controller: 'pnameforms/piece17s'
    resources :piece18s, controller: 'pnameforms/piece18s'
    resources :piece19s, controller: 'pnameforms/piece19s'
    resources :piece20s, controller: 'pnameforms/piece20s'
    resources :piece21s, controller: 'pnameforms/piece21s'
    resources :piece22s, controller: 'pnameforms/piece22s'
    resources :piece23s, controller: 'pnameforms/piece23s'
    resources :piece24s, controller: 'pnameforms/piece24s'
    resources :piece25s, controller: 'pnameforms/piece25s'
  end     

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :seds do
    resources :plays, controller: 'seds/plays'
    resources :scripts, controller: 'seds/scripts'
  end 
  
  root 'pages#home'

end

app/controllers/pnameforms/piece10s_controller.rb
class Pnameforms::Piece10sController < ApplicationController
  before_action :set_piece10, only: [:show, :edit, :update, :destroy]

  # GET /piece10s
  # GET /piece10s.json
  def index
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10s = @pnameform.piece10s
  end

  # GET /piece10s/10
  # GET /piece10s/10.json
  def show
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10s = Piece10.all    
  end

  # GET /piece10s/new
  def new
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10 = current_user.piece10s.build
  end

  # GET /piece10s/10/edit
  def edit
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10.pnameform = @pnameform 
  end

  # POST /piece10s
  # POST /piece10s.json
  def create
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10 = current_user.piece10s.build(piece10_params)
    @piece10.pnameform = @pnameform 

    respond_to do |format|
      if @piece10.save
        format.html { redirect_to pnameform_piece10s_path(@pnameform), notice: 'Piece10 was successfully created.' }
        format.json { render :show, status: :created, location: @piece10 }
      else
        format.html { render :new }
        format.json { render json: @piece10.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piece10s/10
  # PATCH/PUT /piece10s/10.json
  def update
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10.pnameform = @pnameform 

    respond_to do |format|
      if @piece10.update(piece10_params)
        format.html { redirect_to pnameform_piece10s_path(@pnameform), notice: 'Piece10 was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece10 }
      else
        format.html { render :edit }
        format.json { render json: @piece10.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piece10s/10
  # DELETE /piece10s/10.json
  def destroy
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece10 = Piece10.find(params[:id])
    title = @piece10.name

    if @piece10.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to pnameform_piece10s_path(@pnameform)
    else
      flash[:error] = "There was an error deleting."
      render :show 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece10
      @piece10 = Piece10.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece10_params
      params.require(:piece10).permit(:name, :user_id)
    end
end

app/controllers/pnameforms/piece11s_controller.rb
class Pnameforms::Piece11sController < ApplicationController
  before_action :set_piece11, only: [:show, :edit, :update, :destroy]

  # GET /piece11s
  # GET /piece11s.json
  def index
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11s = @pnameform.piece11s
  end

  # GET /piece11s/11
  # GET /piece11s/11.json
  def show
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11s = Piece11.all    
  end

  # GET /piece11s/new
  def new
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11 = current_user.piece11s.build 
  end

  # GET /piece11s/11/edit
  def edit
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11.pnameform = @pnameform 
  end

  # POST /piece11s
  # POST /piece11s.json
  def create
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11 = current_user.piece11s.build(piece11_params)
    @piece11.pnameform = @pnameform 

    respond_to do |format|
      if @piece11.save
        format.html { redirect_to pnameform_piece11s_path(@pnameform), notice: 'Piece11 was successfully created.' }
        format.json { render :show, status: :created, location: @piece11 }
      else
        format.html { render :new }
        format.json { render json: @piece11.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piece11s/11
  # PATCH/PUT /piece11s/11.json
  def update
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11.pnameform = @pnameform 

    respond_to do |format|
      if @piece11.update(piece11_params)
        format.html { redirect_to pnameform_piece11s_path(@pnameform), notice: 'Piece11 was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece11 }
      else
        format.html { render :edit }
        format.json { render json: @piece11.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piece11s/11
  # DELETE /piece11s/11.json
  def destroy
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece11 = Piece11.find(params[:id])
    title = @piece11.name

    if @piece11.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to pnameform_piece11s_path(@pnameform)
    else
      flash[:error] = "There was an error deleting."
      render :show 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece11
      @piece11 = Piece11.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece11_params
      params.require(:piece11).permit(:name, :user_id)
    end
end

app/controllers/pnameforms/piece12s_controller.rb
class Pnameforms::Piece12sController < ApplicationController
  before_action :set_piece12, only: [:show, :edit, :update, :destroy]

  # GET /piece12s
  # GET /piece12s.json
  def index
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12s = @pnameform.piece12s
  end

  # GET /piece12s/12
  # GET /piece12s/12.json
  def show
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12s = Piece12.all    
  end

  # GET /piece12s/new
  def new
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12 = current_user.piece12s.build
  end

  # GET /piece12s/12/edit
  def edit
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12.pnameform = @pnameform 
  end

  # POST /piece12s
  # POST /piece12s.json
  def create
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12 = current_user.piece12s.build(piece12_params)
    @piece12.pnameform = @pnameform 

    respond_to do |format|
      if @piece12.save
        format.html { redirect_to pnameform_piece12s_path(@pnameform), notice: 'Piece12 was successfully created.' }
        format.json { render :show, status: :created, location: @piece12 }
      else
        format.html { render :new }
        format.json { render json: @piece12.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piece12s/12
  # PATCH/PUT /piece12s/12.json
  def update
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12.pnameform = @pnameform 

    respond_to do |format|
      if @piece12.update(piece12_params)
        format.html { redirect_to pnameform_piece12s_path(@pnameform), notice: 'Piece12 was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece12 }
      else
        format.html { render :edit }
        format.json { render json: @piece12.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piece12s/12
  # DELETE /piece12s/12.json
  def destroy
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece12 = Piece12.find(params[:id])
    title = @piece12.name

    if @piece12.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to pnameform_piece12s_path(@pnameform)
    else
      flash[:error] = "There was an error deleting."
      render :show 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece12
      @piece12 = Piece12.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece12_params
      params.require(:piece12).permit(:name, :user_id)
    end
end

app/controllers/pnameforms/piece13s_controller.rb
class Pnameforms::Piece13sController < ApplicationController
  before_action :set_piece13, only: [:show, :edit, :update, :destroy]

  # GET /piece13s
  # GET /piece13s.json
  def index
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13s = @pnameform.piece13s
  end

  # GET /piece13s/13
  # GET /piece13s/13.json
  def show
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13s = Piece13.all    
  end

  # GET /piece13s/new
  def new
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13 = current_user.piece13s.build
  end

  # GET /piece13s/13/edit
  def edit
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13.pnameform = @pnameform 
  end

  # POST /piece13s
  # POST /piece13s.json
  def create
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13 = current_user.piece13s.build(piece13_params)
    @piece13.pnameform = @pnameform 

    respond_to do |format|
      if @piece13.save
        format.html { redirect_to pnameform_piece13s_path(@pnameform), notice: 'Piece13 was successfully created.' }
        format.json { render :show, status: :created, location: @piece13 }
      else
        format.html { render :new }
        format.json { render json: @piece13.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piece13s/13
  # PATCH/PUT /piece13s/13.json
  def update
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13.pnameform = @pnameform 

    respond_to do |format|
      if @piece13.update(piece13_params)
        format.html { redirect_to pnameform_piece13s_path(@pnameform), notice: 'Piece13 was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece13 }
      else
        format.html { render :edit }
        format.json { render json: @piece13.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piece13s/13
  # DELETE /piece13s/13.json
  def destroy
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece13 = Piece13.find(params[:id])
    title = @piece13.name

    if @piece13.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to pnameform_piece13s_path(@pnameform)
    else
      flash[:error] = "There was an error deleting."
      render :show 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece13
      @piece13 = Piece13.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece13_params
      params.require(:piece13).permit(:name, :user_id)
    end
end

app/controllers/pnameforms/piece14s_controller.rb
class Pnameforms::Piece14sController < ApplicationController
  before_action :set_piece14, only: [:show, :edit, :update, :destroy]

  # GET /piece14s
  # GET /piece14s.json
  def index
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14s = @pnameform.piece14s
  end

  # GET /piece14s/14
  # GET /piece14s/14.json
  def show
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14s = Piece14.all    
  end

  # GET /piece14s/new
  def new
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14 = current_user.piece14s.build
  end

  # GET /piece14s/14/edit
  def edit
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14.pnameform = @pnameform 
  end

  # POST /piece14s
  # POST /piece14s.json
  def create
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14 = current_user.piece14s.build(piece14_params)
    @piece14.pnameform = @pnameform 

    respond_to do |format|
      if @piece14.save
        format.html { redirect_to pnameform_piece14s_path(@pnameform), notice: 'Piece14 was successfully created.' }
        format.json { render :show, status: :created, location: @piece14 }
      else
        format.html { render :new }
        format.json { render json: @piece14.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piece14s/14
  # PATCH/PUT /piece14s/14.json
  def update
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14.pnameform = @pnameform 

    respond_to do |format|
      if @piece14.update(piece14_params)
        format.html { redirect_to pnameform_piece14s_path(@pnameform), notice: 'Piece14 was successfully updated.' }
        format.json { render :show, status: :ok, location: @piece14 }
      else
        format.html { render :edit }
        format.json { render json: @piece14.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piece14s/14
  # DELETE /piece14s/14.json
  def destroy
    @pnameform = Pnameform.find(params[:pnameform_id]) 
    @piece14 = Piece14.find(params[:id])
    title = @piece14.name

    if @piece14.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to pnameform_piece14s_path(@pnameform)
    else
      flash[:error] = "There was an error deleting."
      render :show 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece14
      @piece14 = Piece14.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piece14_params
      params.require(:piece14).permit(:name, :user_id)
    end
end

app/views/pnameforms/edit.html.erb
<h1>Titles</h1>

<%= render 'form' %>

<%= link_to 'Back', pnameform_path %>

app/views/pnameforms/index.html.erb
<h1>My Database</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pnameforms.each do |pnameform| %>
          <tr>
            <% if pnameform.user == current_user %>
              <td><%= pnameform.user.email if pnameform.user %></td>
              <td><%= link_to 'Add & Update', pnameform %></td>
              <td><%= link_to 'Edit Title Names', edit_pnameform_path(pnameform) %></td> 
            <% end %>   
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

  

app/views/pnameforms/show.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Play Database</h1></center>
<br>
<div style "float: left"> 
  <table class="table table-bordered">
    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname1 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece1s.map{|piece1| piece1.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname1.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece1s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname2 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece2s.map{|piece2| piece2.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname2.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece2s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname3 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece3s.map{|piece3| piece3.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname3.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece3s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname4 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece4s.map{|piece4| piece4.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname4.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece4s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname5 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece5s.map{|piece5| piece5.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname5.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece5s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname6 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece6s.map{|piece6| piece6.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname6.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece6s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname7 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece7s.map{|piece7| piece7.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname7.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece7s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname8 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece8s.map{|piece8| piece8.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname8.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece8s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname9 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece9s.map{|piece9| piece9.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname9.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece9s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname10 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece10s.map{|piece10| piece10.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname10.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece10s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname11 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece11s.map{|piece11| piece11.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname11.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece11s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname12 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece12s.map{|piece12| piece12.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname12.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece12s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname13 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece13s.map{|piece13| piece13.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname13.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece13s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname14 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece14s.map{|piece14| piece14.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname14.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece14s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname15 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece15s.map{|piece15| piece15.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname15.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece15s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname16 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece16s.map{|piece16| piece16.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname16.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece16s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname17 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece17s.map{|piece17| piece17.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname17.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece17s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname18 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece18s.map{|piece18| piece18.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname18.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece18s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname19 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece19s.map{|piece19| piece19.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname19.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece19s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname20 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece20s.map{|piece20| piece20.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname20.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece20s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname21 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece21s.map{|piece21| piece21.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname21.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece21s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname22 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece22s.map{|piece22| piece22.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname22.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece22s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname23 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece23s.map{|piece23| piece23.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname23.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece23s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname24 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece24s.map{|piece24| piece24.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname24.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece24s_path(@pnameform) %>
      <% end %></td>  
    </tr>

    <tr>
      <td rowspan="3"><strong><%= @pnameform.pname25 %></strong></td>  
    </tr>
    <tr>    
      <td><strong><%= @piece25s.map{|piece25| piece25.name}.join(", ") %></strong></td>          
    </tr>        
      <td><% unless @pnameform.pname25.blank? %> 
        <%= link_to "Add or Edit", pnameform_piece25s_path(@pnameform) %>
      <% end %></td>  
    </tr>
  </table>                      
</div> 


<%= link_to 'Edit', edit_pnameform_path(@pnameform) %> |
<%= link_to 'Back', pnameforms_path %>